### PR TITLE
Expose WiFi Attribute

### PR DESCRIPTION
**Pull request by brentru**
Exposing wifi attribute so wrapper libraries (AWS IoT, Adafruit IO) which create a `minimqtt` object can access WiFiManager and ESP32SPI (via `client.wifi.esp`) attributes.

### CODE REVIEW

**Comment by brentru** [comment]
@ladyada  this only effects the check for a `ESPSPI_WiFiManager`. Other `network_manager`'s (when we make them) would be detected and handled separately. 


```
        network_manager_type = str(type(network_manager))
        if 'ESPSPI_WiFiManager' in network_manager_type:
            self.wifi = network_manager
        else:
            raise TypeError("This library requires a NetworkManager object.")
```

**Comment by ladyada** [comment]
yeah but if its exposed, then people would rely on it?

**Comment by brentru** [comment]
@ladyada  I don't think user-code will rely on this....Possibly a better method would be checking the `esp`'s version from code if an `esp` is used, instead of relying on the MiniMQTT client.

**Comment by brentru** [comment]
@ladyada I don't think exposing from user-code would be a good idea, since libraries using a MiniMQTT object should be able to check `set_psk` and `set_crt` booleans (https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT/blob/master/adafruit_aws_iot.py#L82) on initialization...

I _could_ pass in the `wifi` object to the library's init instead.

**Comment by brentru** [comment]
Closing in favor of https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT/pull/4

**Pull request closed without merging**
