### PR TITLE
Make loop() in esp32spi implementation non-blocking

### PR DESCRIPTION
**Pull request by dlizotte-uwo**
Have been having a discussion with @brentru about an issue with the esp32spi implementation of `loop()` always blocking until the end of the keepalive period. We think raising `OSError(errno.ETIMEDOUT)` at the right point may fix that issue. Also replaces some `%x` format codes with `%s` in the logging statements because `bytearray`s can't be formatted with `%s`. (The `%s` is ugly but it works.)

### CODE REVIEW

**Comment by brentru** [comment]
@dlizotte-uwo Great work - thank you for the PR! I exercised the client against the issue in https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/68 by removing the calls to publish within the `while True` loop, and just pumped the message queue:

```
# Connect the client to the MQTT broker.
print("Connecting to Adafruit IO...")
mqtt_client.connect()

photocell_val = 0
while True:
    # Poll the message queue
    mqtt_client.loop()
```

On `master`, it stalls within `_exact_recv` which was the behavior described in #68. 

On this pull request, it sends a `PINGREQ` and gets a `PINGRESP` to keep the connection with the broker open.
```
959.437: DEBUG - _sock_exact_recv timeout
959.938: DEBUG - KeepAlive period elapsed - requesting a PINGRESP from the server...
959.94: DEBUG - Sending PINGREQ
960.146: DEBUG - Got PINGRESP
961.851: DEBUG - _sock_exact_recv timeout
```

**Review by brentru — CHANGES_REQUESTED** [review]
@dlizotte-uwo The CI is currently failing on running the black formatter: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/69/checks?check_run_id=1905751739#step:11:22

Could you run formatting tools on this pull request (https://learn.adafruit.com/improve-your-code-with-pylint) so I can merge it in?

Thank you for the contribution.

**Review by brentru — APPROVED** [review]
Checks passing, lgtm!

**Comment by dlizotte-uwo** [comment]
OK great! Thanks for walking me though the process.

**Pull request merged**
